site_name: videobeaux
site_description: The friendly multilateral video toolkit built for artists by artists.
site_url: https://schwwaaa.github.io/videobeaux/

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Effects: effects.md
  - Utilities: utilities.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

repo_url: https://github.com/schwwaaa/videobeaux
plugins:
  - search